name: NuGet Publish

on:
  push:
    branches:
      - master
    paths:
      - 'Source/**'
      - 'Samples/**'
      - 'Tests/**'
      - 'Scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Source/**'
      - 'Samples/**'
      - 'Tests/**'
      - 'Scripts/**'
      - '.github/workflows/**'
  release:
    types: [published] # Triggered when a release is published via GitHub Releases UI or gh CLI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to read all tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build and Test
        run: |
          echo "Running build script..."
          dotnet ${{ github.workspace }}/Scripts/Build.cs
          
          echo "Running integration tests..."
          cd Tests
          ./test-both-versions.sh

      - name: Check if version already published (Releases only)
        if: github.event_name == 'release'
        run: dotnet ${{ github.workspace }}/Scripts/CheckVersion.cs

      - name: Publish to NuGet.org (Releases only)
        if: github.event_name == 'release'
        run: |
          dotnet nuget push LocalNuGetFeed/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages-${{ github.run_number }}
          path: LocalNuGetFeed/*.nupkg